import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import { ToastContainer } from "react-toastify";
import "./globals.css";

=======
import "./globals.css";
import Navbar from "@/components/Navbar";
>>>>>>> 997d0552bf75fc1556cef6c0a4338a8a3f61de73
import Footer from "@/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <ToastContainer/>
        <main>{children}</main>
=======
        <Navbar />
        <main className="pt-16">{children}</main>
>>>>>>> 997d0552bf75fc1556cef6c0a4338a8a3f61de73
        <Footer />
      </body>
    </html>
  );
}
